class BaseAppError(Exception): ...

class NoCommitError(BaseAppError): ...
class CommitError(BaseAppError): ...

class ExcelExtractError(BaseAppError): ...
class ParseSheduleError(BaseAppError): ...

class SheduleUpdateError(NoCommitError): ...